### ISSUE TITLE
matlab installation issues

### ISSUE THREAD

**Issue by eljuligallego** [asuardi/protoip#2]
hello @asuardi and @bulatkhusainov,

i managed to install the matlab protoip but i had some issues with the installer due some files are missing(mostly tcl scripts) in the protoip_matlab_installer.m file.

also the urlwrite function is not working with the https github domain due missing certifications (matlab recommend websave function).

 I'll try with cloning the git code because seems more complete version but I'm not sure if it is correct.

Thanks,
regards.

**Comment by eljuligallego** [comment]
the first issue Ifound is the instructions here:

https://github.com/asuardi/protoip/wiki/PL_template_design_flow

give me some errors in args executing the matlab_vivado.tcl:

ip_design_test('project_name','my_project0','type_test','c','num_test',1)
 
****** Vivado v2015.4 (64-bit) 
  **** SW Build 1412921 on Wed Nov 18 09:43:45 MST 2015 
  **** IP Build 1412160 on Tue Nov 17 13:47:24 MST 2015 
    ** Copyright 1986-2015 Xilinx, Inc. All Rights Reserved. 
 
source {C:\Users\julian\Documents\MATLAB\protoip-master\protoip_matlab_interface\matlab_vivado.tcl} 
# set command_name [lindex $argv 0] 
# set tmp_str "tclapp::icl::protoip::" 
# set tmp_str $tmp_str$command_name 
# set command_name $tmp_str 
# set arguments "" 
# for {set i 1} {$i < [llength $argv]} {incr i 2} { 
# 	set dash "-" 
# 	set arg_type [lindex $argv $i] 
# 	set arg_type $dash$arg_type 
# 	set arg_value [lindex $argv [expr $i + 1]] 
#  
# 	set arguments [concat $arguments $arg_type $arg_value] 
#  
# } 
# eval $command_name $arguments 
 -E- option '-num_test' is not a valid option. Use the -usage option for more details 
 -E- option '1' is not a valid option. Use the -usage option for more details 
 -E- some error(s) happened. Cannot continue. Use the -usage option for more details 
    while executing 
"error " -E- some error(s) happened. Cannot continue. Use the -usage option for more details"" 
    invoked from within 
"if {$error} { 
    error " -E- some error(s) happened. Cannot continue. Use the -usage option for more details" 
  }" 
    (procedure "::tclapp::icl::protoip::ip_design_test::ip_design_test" line 324) 
    invoked from within 
"::tclapp::icl::protoip::ip_design_test::ip_design_test -project_name my_project0 -type_test c -num_test 1" 
    ("uplevel" body line 1) 
    invoked from within 
"uplevel [concat ::tclapp::icl::protoip::ip_design_test::ip_design_test $args]" 
    (procedure "tclapp::icl::protoip::ip_design_test" line 20) 
    invoked from within 
"tclapp::icl::protoip::ip_design_test -project_name my_project0 -type_test c -num_test 1" 
    ("eval" body line 1) 
    invoked from within 
"eval $command_name $arguments" 
    (file "C:\Users\julian\Documents\MATLAB\protoip-master\protoip_matlab_interface\matlab_vivado.tcl" line 21)

**Comment by eljuligallego** [comment]
running the tcl commands instead the matlab scripts I was able to finish all the steps.

It seems a problem with my matlab-vivado configuration..

**Comment by bulatkhusainov** [comment]
Dear @eljuligallego 

Many thanks identifying the problem. I will have a look on Matlab interface and update you on this.

Bulat

**Comment by bulatkhusainov** [comment]
Dear @eljuligallego 

The problem was due to a bug in instructions. Please try updated instructions from here: https://github.com/asuardi/protoip/wiki/PL_template_design_flow

Bulat
