### ISSUE TITLE
zedboard configuration to test prototype in PL

### ISSUE THREAD

**Issue by eljuligallego** [asuardi/protoip#3]
Hi @asuardi and @bulatkhusainov ,

I was able to generate the prototype project for the PL but the configuring zedboard [link](https://github.com/asuardi/protoip/wiki/Zedboard)
 the first link about configure the zedboard is missing and I don't the steps needed for configure the board to be able to test the design.

My main question is how is configured the PS part to be able to establish the communication between the zedboard and the computer. 

I opened the vivado project and I have a prototype project with the Processing system inside and my foo block connected trougth AXI so I can generate the .bit to program the FPGA part but for the processor I'm not sure about how to do it.

with my little experience usually with this board it has to boot the system from a boot memory device (like the sd card) with the .bit inside for programing the logic part. How is in this case?.

thanks,
regards.

**Comment by bulatkhusainov** [comment]
Hi @eljuligallego 

There is no need to specifically configure the Zedboard. Just make sure that SD card is unplugged. Connect JTAG-USB cable (it is labelled PROG on the board), Ethernet cable and power supply.  

There is also no need to configure PS manually. When you call "ip_prototype_load" function, your bitstream is uploaded to FPGA (directly via JTAG, no need for SD card). Following this PS will also be programmed with Protoip automatically. 

Then you should be able to call "ip_prototype_test" function to test your implementation. Your results should appear in ./ip_prototype/test/results folder. Please let me know if you have any issues.

**Comment by bulatkhusainov** [comment]
For configuring interface go to: https://github.com/asuardi/protoip/wiki/Configuring_interfaces
