### ISSUE TITLE
error running example foo

### ISSUE THREAD

**Issue by eljuligallego** [asuardi/protoip#4]
hello @asuardi  and @bulatkhusainov,
running th first example from https://github.com/asuardi/protoip/wiki/PL_template_design_flow I get this error when executes the ip_design_build('project_name','my_project0') :
source run_ippack.tcl -notrace 
INFO: [IP_Flow 19-234] Refreshing IP repositories 
INFO: [IP_Flow 19-1704] No user IP repositories specified 
INFO: [IP_Flow 19-2313] Loaded Vivado IP repository 'C:/Xilinx/Vivado/2016.4/data/ip'. 
INFO: [Common 17-206] Exiting Vivado at Fri Sep 15 13:59:45 2017... 
INFO: [HLS 200-112] Total elapsed time: 74.065 seconds; peak allocated memory: 357.300 MB. 
 
couldn't open "ip_design/build/prj/my_project0/solution1/syn/report/foo_foo_user_csynth.rpt": no such file or directory 
    while executing 
"open $target_file" 
    (procedure "::tclapp::icl::protoip::ip_design_build::make_ip_design_read..." line 252) 
    invoked from within 
"::tclapp::icl::protoip::ip_design_build::make_ip_design_readme_txt $project_name" 
.....

Summarizing the file p_design/build/prj/my_project0/solution1/syn/report/foo_foo_user_csynth.rpt is not found but if I look in the folder the file that exist is foo_user_csynth.rpt.

also taking a look at the script https://github.com/Xilinx/XilinxTclStore/blob/2016.4/tclapp/icl/protoip/ip_design_build.tcl in project_name function line (644 and above) it readds the  foo_csynth.rpt for extract timing, resource information and then reads the foo_foo_user_csynth.rpt for same info.

where could be the error?
thanks
regards.

**Comment by eljuligallego** [comment]
I found the problems. it seems the version 2016.4...

**Comment by DeepakIngole** [comment]
The solution is to uninstall Protoip from TCL store of Vivado and install it again. Now, try to build your design.
