### ISSUE TITLE
SOC_template_design_flow guide errata

### ISSUE THREAD

**Issue by eljuligallego** [asuardi/protoip#5]
Hi,
I found a errata in https://github.com/asuardi/protoip/wiki/SOC_template_design_flow
for the tcl script guide.

in step 5 the make template create an PL project instead of a SOC project. I tried:

icl::protoip::make_template -type SOC -project_name my_project0 -input x0:3:fix:10:6 -input x1:7:fix:10:6 -output y0:4:fix:10:6 -soc_input soc_x0:1 -soc_output soc_y0:2 but give errors and there is no example for this instrucction. 

I was able to create the project with the matlab script and run then the TCL code.

regards.

**Comment by bulatkhusainov** [comment]
Hi @eljuligallego ,

Thanks for pointing this out.

Regards,
Bulat
